### ISSUE TITLE
handler "openvpn pack clients" not executed, zip archives not created

### ISSUE THREAD

**Issue by apiening** [Stouts/Stouts.openvpn#104]
Even though I have set "openvpn_unified_client_profiles: false", the client package zip files are not created. There is no message from "openvpn pack clients" so it is not executed on my system.

Any idea why that is?
Debian stretch, Stouts.openvpn version 2.4.

**Comment by splendido** [comment]
I also had no zip files created but then got it working.

The task "openvpn pack clients" relies on the `openvpn_clients` list.
In case your're using PAM as I do, you have to fill both the list of clients and pam users:

```yaml
vars:
    openvpn_unified_client_profiles: no # default value
    openvpn_clients: [client_1, client_2, client_3]
    openvpn_use_pam: yes
    openvpn_use_pam_users:
    - { name: client_1, pwd: 'xxxxxx'}
    - { name: client_2, pwd: 'yyyyyy'}
    - { name: client_3, pwd: 'zzzzzz'}
```

**Comment by nkakouros** [comment]
@apiening Did @splendido's suggestion solve it for you?

**Comment by apiening** [comment]
I don't use PAM, so @splendido's suggestion does not apply in my case.
But I have `openvpn_clients:` of course.
The problem still persists for me, but as a workaround I copied over the task which packs the client archives into my playbook like this:
```
- name: openvpn pack clients
    command: zip -j {{item.item}}.zip {{item.item}}.crt {{item.item}}.key {{item.item}}.ovpn ca.crt {{openvpn_tls_key if openvpn_tls_auth else ''}}
    when: item.changed
    with_items: "{{openvpn_clients_changed.results}}"
    args:
      chdir: "{{ openvpn_keydir }}"
```

I still don't understand why it is not triggered in the first place.
