### ISSUE TITLE
openssl.cnf file could be found

### ISSUE THREAD

**Issue by alessandro-molari** [Stouts/Stouts.openvpn#110]
I've included Stdouts.openvpn role in the `site.yml`:

```yaml
- hosts: bridges
  roles:
    - Stouts.openvpn
  vars:
    openvpn_server: 10.100.0.0 255.255.255.0
    openvpn_max_clients: 128
    openvpn_keepalive: "10 120"
    openvpn_server_options: # Additional server options
      - "client-to-client"
      - "dev-type tap"
      - "tls-server"
    openvpn_client_options: # Additional client options
      - client-to-client

    openvpn_key_size: 1024

    openvpn_clients: [asd]
    openvpn_clients_revoke: []

    # Use PAM authentication
    openvpn_use_pam: yes
    openvpn_use_pam_users:
      - { name: foo, password: password1 }

    # Whether to embed CA, cert, and key info inside client OVPN config file
    openvpn_unified_client_profiles: yes
```

When I try to run:

```
ansible-playbook -i inventory.yml site.yml
```

I get the following error:

```
TASK [Stouts.openvpn : Generate Clients keys] *********************************************
failed: [b1.cl-ops.it] (item=b1-cl-ops) => {"changed": true, "cmd": ["/etc/openvpn/build-client.sh", "b1-cl-ops"], "delta": "0:00:00.066120", "end": "2018-10-15 14:52:03.733415", "item": "b1-cl-ops", "msg": "non-zero return code", "rc": 1, "start": "2018-10-15 14:52:03.667295", "stderr": "**************************************************************\n  No /etc/openvpn/easy-rsa/openssl.cnf file could be found\n  Further invocations will fail\n**************************************************************\ngrep: /etc/openvpn/easy-rsa/openssl.cnf: No such file or directory", "stderr_lines": ["**************************************************************", "  No /etc/openvpn/easy-rsa/openssl.cnf file could be found", "  Further invocations will fail", "**************************************************************", "grep: /etc/openvpn/easy-rsa/openssl.cnf: No such file or directory"], "stdout": "NOTE: If you run ./clean-all, I will be doing a rm -rf on /etc/openvpn/keys\npkitool: KEY_CONFIG (set by the ./vars script) is pointing to the wrong\nversion of openssl.cnf: /etc/openvpn/easy-rsa/openssl.cnf\nThe correct version should have a comment that says: easy-rsa version 2.x", "stdout_lines": ["NOTE: If you run ./clean-all, I will be doing a rm -rf on /etc/openvpn/keys", "pkitool: KEY_CONFIG (set by the ./vars script) is pointing to the wrong", "version of openssl.cnf: /etc/openvpn/easy-rsa/openssl.cnf", "The correct version should have a comment that says: easy-rsa version 2.x"]}

```

In fact this is the content of `/etc/openvpn/easy-rsa`:
![screenshot-2018-54-15 16 54 35 107](https://user-images.githubusercontent.com/336957/46958907-225f9d80-d09b-11e8-8ce3-6e6cb0b3bc37.png)

The installed openssl version is 1.1.0 which doesn't have a specific configuration file and isn't considered by easy-rsa.
