### ISSUE TITLE
Enable static IP for client

### ISSUE THREAD

**Issue by mikysal78** [Stouts/Stouts.openvpn#123]
howto setting ip static for clients?
thanks.

**Comment by nkakouros** [comment]
This is a snippet I use:

```yaml
    openvpn_client_config_dir: /etc/openvpn/client
...
    - name: Add static ip config
      copy:
        content:
          ifconfig-push {{ network.vpn_range | ipaddr(item.0 + 2) | ipaddr('address') }} {{ network.vpn_range | ipaddr('netmask') }}
        dest: "/etc/openvpn/client/{{ item.1 }}"
        owner: nobody
        group: nogroup
      loop: "{{ lookup('indexed_items', openvpn_clients) }}"
```
