### ISSUE TITLE
Upload inline scripts fails

### ISSUE THREAD

**Issue by apiening** [Stouts/Stouts.openvpn#155]
When I populate `openvpn_inline_scripts` like this:
```
openvpn_inline_scripts:
   - name: my-up-script.sh
     content: |
       #!/usr/bin/env
       echo 'Up!' >> "/var/up.log"
```
the task `Upload inline scripts` from the file `tasks/scripts.yml` fails with the error `src and dest are required`. Which is also mentioned in the docs of the template-module: https://docs.ansible.com/ansible/latest/modules/template_module.html

Renaming the module `template` with `copy` in the task, solves the issue and the inline scripts are created.
