### ISSUE TITLE
Default openvpn_use_pam_plugin_distribution variable for Ubuntu

### ISSUE THREAD

**Issue by Friz-zy** [Stouts/Stouts.openvpn#45]
I got a problem with ansible-playbook 2.0.0.2:
looks like it didn't recognize ubuntu trusty and use default value, that produced this error
```
PLUGIN_INIT: could not load plugin shared object /usr/lib/openvpn/openvpn-auth-pam.so: /usr/lib/openvpn/openvpn-auth-pam.so: cannot open shared object file: No such file or directory
```

Today most of all servers use ubuntu >= 14.04, it may be worth to change default variable into new path and leave additional files for previous or add checking that file exists?

**Comment by ksylvan** [comment]
I also support making the default Ubuntu configuration be the one that works for the modern variants, with the exceptions (specified by those variable files) being the older variants.

**Comment by megakoresh** [comment]
Yeah, hit this one too. I had to do add this to `post_tasks` to make it work:
```yaml
- name: Fix broken library link
  file:
    src: /usr/lib/x86_64-linux-gnu/openvpn/plugins/openvpn-plugin-auth-pam.so
    dest: /usr/lib/openvpn/openvpn-auth-pam.so
    state: link
```
