### ISSUE TITLE
zip files not produced.

### ISSUE THREAD

**Issue by xahare** [Stouts/Stouts.openvpn#85]
set these and the playbook wont produce zip files. with only openvpn_clients and openvpn_use_pam set, it does. the goal was to have a server behind dhcp and nat that could reliably be reached from the outside.
the full Vagrantfile, playbooks, and a script session log are at the gist below.

role is at commit 1d08b2354c6ef47f2273c68d638cfca013bac07a Tue Feb 14 09:05:23 2017 -0800

```
    openvpn_use_pam: no
    openvpn_server: 
    openvpn_clients: [server,client]
    openvpn_server_options:
      - mode server
      - ifconfig 10.8.0.1 255.255.255.0
      - push "route-gateway 10.8.0.1"
      - ifconfig-pool 10.8.0.128 10.8.0.250 255.255.255.0
      - client_config_dir /etc/openvpn/ccd

```
https://gist.github.com/xahare/390e5f4645cdaee2f90011e26b9c5c50
