### ISSUE TITLE
Stouts.openvpn doesn't work on debian stretch

### ISSUE THREAD

**Issue by jpalczewski** [Stouts/Stouts.openvpn#86]
Hello,

I just want to leave a note that role fails on debian stretch at "Read CA cert" task - there's openssl from 1.1 branch and whichopenssl fails to locate appropriate config file.

It was easier for me to use debian jessie at the moment, however maybe just creating simple symlink to openssl.cnf(which is default choice if openssl 1.0.x or 9.x is not found) would be satisfactory solution in this case.

**Comment by I7K** [comment]
Thanks

**Comment by mnzt** [comment]
You can circumvent this quickly with
```
pre_tasks:
    - name: openssl config symlink
      file:
        src: "/etc/openvpn/easy-rsa/openssl-1.0.0.cnf"
        dest: "/etc/openvpn/easy-rsa/openssl.cnf"
        state: link
```
